services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init/testdb.sql:/docker-entrypoint-initdb.d/testdb.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootpassword | grep 'mysqld is alive' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  phpmyadminGBD:
    image: phpmyadmin:latest
    container_name: phpmyadmin_app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - db

  backend_app:
    build: ./backend-app
    container_name: backend_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend-app:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  frontend_app:
    build: ./frontend-app
    container_name: frontend_app
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      backend_app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - ./frontend-app:/app
      - /app/node_modules

volumes:
  db_data:
